version: "3"

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - infra

  jenkins:
    image: jenkins/jenkins:lts-centos
    container_name: jenkins
    restart: always
    ports: 
      - "${JENKINS_PORT}:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /usr/lib/jvm/java:/usr/lib/jvm/java
    networks:
      - infra

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes: 
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/mysql:/var/lib/mysql
    networks:
      - infra
networks:
  infra:
